galaxy_info:
  role_name: vector
  namespace: sofin
  author: SofinRA
  description: Role for installation and managing Vector

  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial
    - name: Debian
      versions:
        - bullseye
        - buster
        - stretch
        - jessie
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags:
    - vector
    - database
    - sql

dependencies: []
