# Molecule managed


{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}



RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get upgrade -y && apt-get install -y systemd systemd-sysv  init && apt-get clean; \
    elif [ $(command -v yum) ]; then sed -i 's/^\(tsflags=*\)/# \1/g' /etc/yum.conf && yum makecache fast && yum upgrade -y && yum makecache fast && yum install -y initscripts && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; fi

#RUN set -xe \
#  && groupadd -r ${ANSIBLE_USER} \
#  && groupadd -r ${DEPLOY_GROUP} \
#  && useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} \
#  && usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} \
#  && echo "%${DEPLOY_GROUP} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ansible

#RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
#    systemd-tmpfiles-setup.service ] || rm -f $i; done); \
#    rm -rf /lib/systemd/system/multi-user.target.wants/*;\
#    rm -rf /etc/systemd/system/*.wants/*;\
#    rm -rf /lib/systemd/system/local-fs.target.wants/*; \
#    rm -rf /lib/systemd/system/sockets.target.wants/*udev*; \
#    rm -rf /lib/systemd/system/sockets.target.wants/*initctl*; \
#    rm -rf /lib/systemd/system/basic.target.wants/*;\
#    rm -rf /lib/systemd/system/anaconda.target.wants/*;


VOLUME [ "/sys/fs/cgroup" ]
CMD ["{{ item.command | default('/usr/sbin/init') }}"]
