---
# handlers file for lighthouse-role
- name: Nginx start
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
- name: Nginx reload
  become: true
  command: nginx -s reload
