---
all:
  hosts:
    sonar-01:
      ansible_host: 158.160.6.92
    nexus-01:
      ansible_host: 84.201.155.196
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: user
