apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader
  namespace: default
subjects:
- kind: User
  name: awertoss
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-desc-logs
  apiGroup: rbac.authorization.k8s.io
